import type { DemoVideoItem, ProcessVideoResponse } from "../types/video-models";

export const DEMO_VIDEOS: readonly DemoVideoItem[] = [
  {
    youtubeVideoId: "sample-health-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-health-01",
    title: "Reversing Type 2 Diabetes Starts with Ignoring Guidelines | Dr. Sarah Hallberg (TEDx)",
    category: "health",
    targetOutcome: "contested",
    notes: "Dr. Sarah Hallberg explains the hormonal etiology of insulin resistance and challenges standard high-carbohydrate guidelines.",
  },
  {
    youtubeVideoId: "sample-finance-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-finance-01",
    title: "Everything You Need to Know About Finance & Investing | Bill Ackman (Big Think)",
    category: "financial",
    targetOutcome: "high_confidence",
    notes: "Pershing Square CEO Bill Ackman teaches balance sheets, equity financing, debt leverage, and capital allocation.",
  },
  {
    youtubeVideoId: "sample-factcheck-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-factcheck-01",
    title: "How The Immune System Actually Works | Kurzgesagt – In a Nutshell",
    category: "health",
    targetOutcome: "high_confidence",
    notes: "Kurzgesagt visualizes the cellular mechanisms of innate immunity, macrophages, neutrophils, and adaptive memory T-cells.",
  },
];

export const DEMO_LEDGERS: Record<string, ProcessVideoResponse> = {
  "sample-health-01": {
    videoId: "vid_demo_health_01",
    youtubeVideoId: "sample-health-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-health-01",
    title: "Reversing Type 2 Diabetes Starts with Ignoring Guidelines | Dr. Sarah Hallberg (TEDx)",
    processedAt: "2026-09-25T08:30:00.000Z",
    claimsCount: 4,
    verifiedLedger: [
      {
        claimId: "clm_h01_01",
        timestampSeconds: 59,
        rawText: "Obesity is a disease, not a lack of character; it's a hormonal disease, and one of the main ones is insulin.",
        category: "health",
        trustScore: 0.94,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Major endocrinology societies and peer-reviewed literature confirm that obesity and type 2 diabetes are metabolic disorders driven by systemic insulin resistance and endocrine dysregulation.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_scholar",
            sourceUrl: "https://scholar.google.com/scholar?q=obesity+hormonal+disease+insulin+resistance+etiology",
            sourceDomain: "pubmed.ncbi.nlm.nih.gov",
            sourceAuthorityScore: 1.0,
            matchedText: "Type 2 diabetes mellitus and metabolic obesity are fundamentally endocrine disorders characterized by peripheral insulin resistance and progressive pancreatic beta-cell dysfunction.",
            groundingSimilarity: 0.94,
            rawResponseCachePath: "data/cache/clm_h01_01_google_scholar.json",
          },
        ],
      },
      {
        claimId: "clm_h01_02",
        timestampSeconds: 87,
        rawText: "Insulin's job is to drive glucose or blood sugar into the cells where it can be used.",
        category: "health",
        trustScore: 0.96,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Insulin is the primary anabolic hormone responsible for facilitating cellular glucose uptake via GLUT-4 transporters into skeletal muscle and adipose tissue.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_scholar",
            sourceUrl: "https://scholar.google.com/scholar?q=insulin+cellular+glucose+uptake+glut4+translocation",
            sourceDomain: "care.diabetesjournals.org",
            sourceAuthorityScore: 1.0,
            matchedText: "Insulin binds to membrane receptors stimulating intracellular GLUT4 translocation, thereby facilitating blood glucose uptake into peripheral tissues for energetic oxidation.",
            groundingSimilarity: 0.96,
            rawResponseCachePath: "data/cache/clm_h01_02_google_scholar.json",
          },
        ],
      },
      {
        claimId: "clm_h01_03",
        timestampSeconds: 152,
        rawText: "Almost 50% of adult Americans now have diabetes or prediabetes, which is almost 120 million people.",
        category: "health",
        trustScore: 0.92,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "CDC National Diabetes Statistics Reports verify that over 38 million Americans have diabetes and 97.6 million have prediabetes, exceeding 45% of the adult US population.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_scholar",
            sourceUrl: "https://scholar.google.com/scholar?q=cdc+national+diabetes+statistics+report+prevalence",
            sourceDomain: "cdc.gov",
            sourceAuthorityScore: 1.0,
            matchedText: "CDC surveillance indicates 38.4 million people have diabetes and 97.6 million adults aged 18 years or older have prediabetes, representing over 46% of all adult Americans.",
            groundingSimilarity: 0.92,
            rawResponseCachePath: "data/cache/clm_h01_03_google_scholar.json",
          },
        ],
      },
      {
        claimId: "clm_h01_04",
        timestampSeconds: 209,
        rawText: "Insulin makes us hungry and is our fat storage hormone, making food much more likely to be stored as fat.",
        category: "health",
        trustScore: 0.74,
        confidenceLabel: "contested",
        verifiedClaimText: "Insulin actively suppresses lipolysis and promotes fatty acid esterification, but the carbohydrate-insulin model of hyperphagic hunger is heavily contested in energy balance literature.",
        conflictingClaims: [
          "Consensus metabolic trials by the NIH and Hall et al. demonstrate that isocaloric macronutrient variations do not produce meaningful differences in long-term body fat loss, disputing the hypothesis that insulin alone causes positive energy imbalance.",
        ],
        evidence: [
          {
            sourceType: "google_scholar",
            sourceUrl: "https://scholar.google.com/scholar?q=carbohydrate+insulin+model+energy+balance+hall+meta-analysis",
            sourceDomain: "ncbi.nlm.nih.gov",
            sourceAuthorityScore: 1.0,
            matchedText: "While insulin stimulates lipogenesis and suppresses lipolysis biochemically, controlled human inpatient studies indicate energy expenditure and fat loss are governed predominantly by total caloric balance rather than insulin-mediated nutrient trapping.",
            groundingSimilarity: 0.74,
            rawResponseCachePath: "data/cache/clm_h01_04_google_scholar.json",
          },
        ],
      },
    ],
    cacheSummary: {
      videoCacheStatus: "disk_cache_hit",
      cachedClaimsCount: 4,
      liveGroundingCount: 0,
    },
  },
  "sample-finance-01": {
    videoId: "vid_demo_finance_01",
    youtubeVideoId: "sample-finance-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-finance-01",
    title: "Everything You Need to Know About Finance & Investing | Bill Ackman (Big Think)",
    processedAt: "2026-09-25T08:35:00.000Z",
    claimsCount: 2,
    verifiedLedger: [
      {
        claimId: "clm_f01_01",
        timestampSeconds: 128,
        rawText: "By borrowing money instead of selling more stock, we keep more equity so if the business is successful we end up with a bigger percentage of profits.",
        category: "financial",
        trustScore: 0.92,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Corporate financial theory confirms that debt leverage preserves equity ownership, magnifying return on equity (ROE) if return on capital exceeds the cost of debt.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_finance",
            sourceUrl: "https://www.google.com/finance/quote/financial-leverage-cost-of-debt-capital-structure",
            sourceDomain: "finance.google.com",
            sourceAuthorityScore: 1.0,
            matchedText: "Financial leverage through fixed debt obligations avoids shareholder dilution and increases earnings per share during profitable periods, subject to solvency risk.",
            groundingSimilarity: 0.92,
            rawResponseCachePath: "data/cache/clm_f01_01_google_finance.json",
          },
        ],
      },
      {
        claimId: "clm_f01_02",
        timestampSeconds: 143,
        rawText: "A balance sheet tells you where the company stands: what your assets are, what your liabilities are, and what your net worth or shareholder equity is.",
        category: "financial",
        trustScore: 0.98,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Standard accounting frameworks (GAAP and IFRS) define the fundamental balance sheet equation as Assets = Liabilities + Shareholder Equity.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_finance",
            sourceUrl: "https://www.google.com/finance/quote/balance-sheet-accounting-standards-gaap",
            sourceDomain: "finance.google.com",
            sourceAuthorityScore: 1.0,
            matchedText: "The balance sheet provides a financial snapshot of a firm's financial position at a specific point in time, systematically equating total assets with liabilities plus shareholder equity.",
            groundingSimilarity: 0.98,
            rawResponseCachePath: "data/cache/clm_f01_02_google_finance.json",
          },
        ],
      },
    ],
    cacheSummary: {
      videoCacheStatus: "disk_cache_hit",
      cachedClaimsCount: 2,
      liveGroundingCount: 0,
    },
  },
  "sample-factcheck-01": {
    videoId: "vid_demo_factcheck_01",
    youtubeVideoId: "sample-factcheck-01",
    youtubeUrl: "https://www.youtube.com/watch?v=sample-factcheck-01",
    title: "How The Immune System Actually Works | Kurzgesagt – In a Nutshell",
    processedAt: "2026-09-25T08:40:00.000Z",
    claimsCount: 3,
    verifiedLedger: [
      {
        claimId: "clm_fc01_01",
        timestampSeconds: 104,
        rawText: "Guard cells known as macrophages guard every border region of the body and can devour up to 100 intruders each.",
        category: "health",
        trustScore: 0.95,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Macrophages are specialized tissue-resident phagocytes that continuously patrol epithelial boundaries, engulfing and destroying cellular debris and microbial pathogens.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_fact_check",
            sourceUrl: "https://toolbox.google.com/factcheck/explorer/search/macrophage%20innate%20immunity%20phagocytosis",
            sourceDomain: "ncbi.nlm.nih.gov",
            sourceAuthorityScore: 1.0,
            matchedText: "Macrophages function as frontline sentinels in innate host defense, capable of ingesting numerous microbial targets through actin-mediated phagocytosis.",
            groundingSimilarity: 0.95,
            rawResponseCachePath: "data/cache/clm_fc01_01_google_fact_check.json",
          },
        ],
      },
      {
        claimId: "clm_fc01_02",
        timestampSeconds: 155,
        rawText: "Neutrophils are so deadly that they evolved to commit suicide after five days to prevent causing too much damage.",
        category: "health",
        trustScore: 0.91,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Neutrophils possess cytotoxic granules that can cause collateral host tissue injury, and they have an evolutionary short lifespan ending in programmed apoptosis.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_fact_check",
            sourceUrl: "https://toolbox.google.com/factcheck/explorer/search/neutrophil%20apoptosis%20tissue%20damage",
            sourceDomain: "nature.com",
            sourceAuthorityScore: 1.0,
            matchedText: "Neutrophils undergo constitutive apoptosis within days of differentiation, a vital homeostatic mechanism preventing sustained degranulation and chronic tissue necrosis.",
            groundingSimilarity: 0.91,
            rawResponseCachePath: "data/cache/clm_fc01_02_google_fact_check.json",
          },
        ],
      },
      {
        claimId: "clm_fc01_03",
        timestampSeconds: 227,
        rawText: "Some activated T cells become memory T cells that stay in the lymph node and make you practically immune against this enemy.",
        category: "health",
        trustScore: 0.96,
        confidenceLabel: "high_confidence",
        verifiedClaimText: "Antigen-stimulated CD4+ and CD8+ T cells differentiate into long-lived memory T cell populations that mediate rapid immunological recall protection.",
        conflictingClaims: [],
        evidence: [
          {
            sourceType: "google_fact_check",
            sourceUrl: "https://toolbox.google.com/factcheck/explorer/search/memory%20t%20cells%20long%20term%20immunity",
            sourceDomain: "who.int",
            sourceAuthorityScore: 1.0,
            matchedText: "Memory T lymphocytes persist for years following primary antigen exposure, enabling swift, targeted effector responses that prevent recurrent infectious illness.",
            groundingSimilarity: 0.96,
            rawResponseCachePath: "data/cache/clm_fc01_03_google_fact_check.json",
          },
        ],
      },
    ],
    cacheSummary: {
      videoCacheStatus: "disk_cache_hit",
      cachedClaimsCount: 3,
      liveGroundingCount: 0,
    },
  },
};
